version: "3.9"  # Use a recent version

services:
  discord-bot:
    build: .  # Assuming your Dockerfile is in the root
    restart: always  # Handles restarts (useful for Kubernetes)
    env_file:
      - .env  # Load environment variables from a fil
