name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR  # Adjusted for GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io      # Target GHCR
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}  
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/joshhmann/discordgemini-js:latest  # Adjusted Tag



